name: ish_lunc
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - attrs=25.4.0=pyh71513ae_0
  - blas=2.137=openblas
  - blas-devel=3.9.0=37_h1ea3ea9_openblas
  - blosc=1.21.6=hf7d4471_0
  - bottleneck=1.4.2=py311hf4808d0_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311h4eded50_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - contourpy=1.3.1=py311hdb19cb5_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - fiona=1.10.1=py311h7934f7d_1
  - folium=0.20.0=pyhd8ed1ab_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=pyh7db6752_0
  - freetype=2.13.3=h4a9f257_0
  - freexl=2.0.0=hf309648_0
  - fribidi=1.0.10=h36c2ea0_0
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.10.6=h6a678d5_0
  - geotiff=1.7.0=ha59944b_4
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - json-c=0.16=hc379101_0
  - kiwisolver=1.4.8=py311h6a678d5_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libavif=1.1.1=h5eee18b_0
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=37_h0358290_openblas
  - libcurl=8.15.0=hc1efc7f_0
  - libdeflate=1.22=h5eee18b_0
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgdal-core=3.11.0=h177e9c5_1
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libkml=1.3.0=h096b73e_7
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblapacke=3.9.0=37_h6ae95b6_openblas
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.30=h46f56fc_0
  - libpng=1.6.50=h2ed474d_0
  - libspatialite=5.1.0=h798b768_2
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib-base=3.10.6=py311h71dd3da_0
  - minizip=4.0.3=hf59b114_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - networkx=3.5=pyhe01879c_0
  - nomkl=3.0=0
  - numexpr=2.11.0=py311hccd6f0b_1
  - numpy=2.3.3=py311hc213724_1
  - numpy-base=2.3.3=py311hf387b04_1
  - openblas=0.3.30=h5426c36_0
  - openblas-devel=0.3.30=h557178c_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h505adc9_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.3.0=py311hb1c3d2d_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - proj=9.3.1=h4591001_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.22=pyh29332c3_1
  - pyogrio=0.10.0=py311h16bd0e6_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.6.1=py311h76fdc58_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py311h505adc9_0
  - scipy=1.16.2=py311ha592af2_0
  - setuptools=80.9.0=py311h06a4308_0
  - shapely=2.1.1=py311h05a33e2_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - uriparser=0.9.8=h451ca9b_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xerces-c=3.2.4=h6a678d5_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.24.0=py311h3d778a8_0
  - zstd=1.5.7=h11fc155_0
prefix: /root/miniconda3/envs/ish
